---
title: "Generate phenotype file for GWAS in gemma"
author: "Johan Zicola"
date: "`r Sys.Date()`"
output: html_notebook
---

# User input
```{r}

# Directory containing the file with phenotypes
dir_gwas <- "T:/dep_coupland/grp_hancock/johan/GWAS/"

# Name of the file to import. The file is generated by process_chromatinJ_output.Rmd
file_name <- "test_export_df.txt"

# Name of the phenotype indicated in the dataframe (see Lists of phenotypes below)
phenotype <- "Area"

# Name chosen for the output file
name_phenotype <- "Area_nucleus"

```


```{r echo=FALSE}

# List of packages required for this analysis
pkg <- c("ggplot2")

# Check if packages are not installed and assign the
# names of the packages not installed to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]

# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg)) {
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
}

# Library to plot Manhattan plots

library(ggplot2)

# fun_nucleus.R is located in same directory as this script
source("fun_nucleus.R")

```


# Import dataframe
The dataframe should have as first column the accession code (mentioned in the VCF file) in 1st column
and the different phenotypes in other columns. The columns should have a header.

```{r}

file_path <- paste(dir_gwas, file_name, sep="")

df_gwas <- read.table(file_path, header=TRUE, sep="\t")

```

## Lists of phenotypes
```{r}
names(df_gwas)
```


## Export wanted phenotype
```{r}
# Not that df_gwas$phenotype cannot be used as $ does not take variables
variable <- df_gwas[,phenotype]

name_file <- paste(name_phenotype,".tsv", sep="")

path_file <- paste(dir_gwas, name_file, sep="")

write.table(variable, row.names = FALSE, col.names = FALSE, quote = FALSE, file = path_file, sep = "\t")

```


## Export scaled wanted phenotype
```{r}
#normalize data
variable_scaled <- scale(variable)

# Add automatically the suffix "_scaled" when the variable is scaled
name_phenotype_scaled <- paste(name_phenotype, "scaled", sep="_")

name_file_scaled <- paste(name_phenotype_scaled,".tsv", sep="")

path_file <- paste(dir_gwas, name_file_scaled, sep="")

write.table(variable_scaled, row.names = FALSE, col.names = FALSE, quote = FALSE, file = path_file, sep = "\t")

```


## Data plot
```{r}
ggplot.boxplot(df_gwas, "Accession", variable, name_phenotype)+labs(x="Accession",y=name_phenotype)
```


## Normality of residual distribution
```{r}
#Test normality of residual distribution
hist(variable)
```

```{r}
#Test normality of residual distribution
qqnorm(variable)
qqline(variable)

```






